import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { fetchModel } from './modelPack';

/**
 * The shared look of every arena: tiling materials (colour map + normal map, some with a glow map), loaded lazily from the
 * arena packs under /models/arenas, with a plain canvas texture standing in until a pack has arrived (or for good if it
 * cannot be loaded). Arena scenery (arenaMap.ts) asks for materials by name and gets the same stone, sand, ice, wood and
 * basalt on every map; geometry helpers for the cover pieces live here too.
 *
 *   kit.glb       sand, sandbrick, cobble, carved, sandstone, obeliskstone (from the "Arena" scene), snow, ice, frostbrick,
 *                 mossbrick, flagstone, planks, dirt (generated by scripts/prep-arena.mjs)
 *   cinder.glb    the crater (`rim`), horns (`prop_horn_N`), hell textures (lavacrack, basalt, basaltdark, blackbrick, ...)
 *   forge.glb     rock ring (`rim`), lava disc (`lava`), grate disc (`grate`), hell textures
 *   sandstone.glb the stadium shell (`shell_*`), obelisks (`prop_obelisk_N`)
 */

export const KIT_URL = '/models/arenas/kit.glb';
export const arenaPackUrl = (id: string) => `/models/arenas/${id}.glb`;

export function rng(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function canvasTex(w: number, h: number, draw: (g: CanvasRenderingContext2D) => void, repeat?: [number, number]): THREE.CanvasTexture {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  draw(c.getContext('2d')!);
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  if (repeat) {
    t.wrapS = t.wrapT = THREE.RepeatWrapping;
    t.repeat.set(repeat[0], repeat[1]);
    t.anisotropy = 4;
  }
  return t;
}

export const shade = (hex: string, k: number) => {
  const n = parseInt(hex.slice(1), 16);
  const f = (v: number) => Math.max(0, Math.min(255, Math.round(v * k)));
  return `rgb(${f((n >> 16) & 255)},${f((n >> 8) & 255)},${f(n & 255)})`;
};

// ------------------------------------------------------------------ fallback textures (used until a pack arrives, or if it fails)

interface Fallback { base: string; rows: number; cols: number; bond: boolean; kind: 'brick' | 'noise' | 'lava' | 'planks' }
const FALLBACK: Record<string, Fallback> = {
  sand: { base: '#b79b72', rows: 1, cols: 1, bond: false, kind: 'noise' },
  dirt: { base: '#7d6648', rows: 1, cols: 1, bond: false, kind: 'noise' },
  snow: { base: '#dbe6f4', rows: 1, cols: 1, bond: false, kind: 'noise' },
  ice: { base: '#8fc0e6', rows: 3, cols: 3, bond: false, kind: 'noise' },
  sandstone: { base: '#c2ac84', rows: 1, cols: 1, bond: false, kind: 'noise' },
  sandbrick: { base: '#9a968c', rows: 8, cols: 4, bond: true, kind: 'brick' },
  cobble: { base: '#9a9a96', rows: 5, cols: 5, bond: false, kind: 'brick' },
  carved: { base: '#c9b58c', rows: 1, cols: 1, bond: false, kind: 'noise' },
  obeliskstone: { base: '#a9a9a4', rows: 10, cols: 3, bond: true, kind: 'brick' },
  frostbrick: { base: '#8da4c4', rows: 6, cols: 3, bond: true, kind: 'brick' },
  mossbrick: { base: '#8a8a72', rows: 7, cols: 3, bond: true, kind: 'brick' },
  flagstone: { base: '#80846f', rows: 5, cols: 5, bond: false, kind: 'brick' },
  planks: { base: '#8a6a43', rows: 8, cols: 1, bond: false, kind: 'planks' },
  lavacrack: { base: '#1c0d0a', rows: 1, cols: 1, bond: false, kind: 'lava' },
  lavaflow: { base: '#c8400c', rows: 1, cols: 1, bond: false, kind: 'lava' },
  basalt: { base: '#3d3d42', rows: 7, cols: 4, bond: true, kind: 'brick' },
  basaltdark: { base: '#25252a', rows: 1, cols: 1, bond: false, kind: 'noise' },
  blackbrick: { base: '#33363a', rows: 4, cols: 3, bond: true, kind: 'brick' },
  greybrick: { base: '#7c7c7c', rows: 5, cols: 3, bond: true, kind: 'brick' },
  orangerock: { base: '#b9803f', rows: 1, cols: 1, bond: false, kind: 'noise' },
};

function fallbackTexture(name: string): THREE.CanvasTexture {
  const f = FALLBACK[name] ?? FALLBACK.sandstone;
  const size = 256;
  return canvasTex(size, size, (g) => {
    const r = rng(name.length * 7919 + name.charCodeAt(0));
    g.fillStyle = shade(f.base, f.kind === 'brick' ? 0.6 : 1);
    g.fillRect(0, 0, size, size);
    if (f.kind === 'brick') {
      const bh = size / f.rows, bw = size / f.cols;
      for (let y = 0; y < f.rows; y++) {
        const off = f.bond && y % 2 ? bw / 2 : 0;
        for (let x = -1; x < f.cols; x++) {
          g.fillStyle = shade(f.base, 0.85 + r() * 0.3);
          g.fillRect(x * bw + off + 2, y * bh + 2, bw - 4, bh - 4);
        }
      }
    } else if (f.kind === 'planks') {
      for (let y = 0; y < f.rows; y++) {
        g.fillStyle = shade(f.base, 0.8 + r() * 0.4);
        g.fillRect(0, y * (size / f.rows) + 1, size, size / f.rows - 2);
      }
    } else if (f.kind === 'lava') {
      g.strokeStyle = shade(f.base, 4);
      g.lineWidth = 3;
      for (let i = 0; i < 9; i++) {
        g.beginPath();
        let x = r() * size, y = r() * size;
        g.moveTo(x, y);
        for (let s = 0; s < 5; s++) g.lineTo((x += (r() - 0.5) * 90), (y += (r() - 0.5) * 90));
        g.stroke();
      }
    }
    for (let i = 0; i < size * 6; i++) {
      g.fillStyle = r() < 0.5 ? 'rgba(0,0,0,.07)' : 'rgba(255,255,255,.05)';
      g.fillRect(r() * size, r() * size, 1 + r() * 2, 1 + r() * 2);
    }
  });
}

// ------------------------------------------------------------------ packs

interface TexSet {
  map: THREE.Texture;
  normalMap?: THREE.Texture;
  emissiveMap?: THREE.Texture;
  emissive?: THREE.Color;
}
const registry = new Map<string, TexSet>();

interface Binding {
  mat: THREE.MeshStandardMaterial;
  name: string;
  repeat: [number, number];
  normalScale: number;
  glow: number;
}
const bindings = new Set<Binding>();

function parseGlbJson(buf: ArrayBuffer): { json: any; bin: Uint8Array } {
  const dv = new DataView(buf);
  let off = 12, json: any, bin = new Uint8Array(0);
  while (off < buf.byteLength) {
    const len = dv.getUint32(off, true), type = dv.getUint32(off + 4, true);
    const data = new Uint8Array(buf, off + 8, len);
    if (type === 0x4e4f534a) json = JSON.parse(new TextDecoder().decode(data));
    else if (type === 0x004e4942) bin = data;
    off += 8 + len;
  }
  return { json, bin };
}

function decodeImage(bytes: Uint8Array, mime: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const url = URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer], { type: mime }));
    const img = new Image();
    img.onload = () => {
      URL.revokeObjectURL(url);
      resolve(img);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('texture could not be decoded'));
    };
    img.src = url;
  });
}

/** Read the `mat_*` swatch materials of a pack into the texture registry (own decode: orientation and colour space are ours). */
async function registerMaterials(buf: ArrayBuffer): Promise<void> {
  const { json, bin } = parseGlbJson(buf);
  const images = new Map<number, Promise<THREE.Texture>>();
  const tex = (index: number | undefined, srgb: boolean): Promise<THREE.Texture> | undefined => {
    if (index === undefined) return undefined;
    const src = json.textures[index].source as number;
    const key = src * 2 + (srgb ? 1 : 0);
    if (!images.has(key)) {
      const im = json.images[src];
      const bv = json.bufferViews[im.bufferView];
      const bytes = bin.subarray(bv.byteOffset || 0, (bv.byteOffset || 0) + bv.byteLength);
      images.set(key, decodeImage(bytes, im.mimeType).then((img) => {
        const t = new THREE.Texture(img);
        t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
        t.wrapS = t.wrapT = THREE.RepeatWrapping;
        t.generateMipmaps = true;
        t.minFilter = THREE.LinearMipmapLinearFilter;
        t.anisotropy = 4;
        t.needsUpdate = true;
        return t;
      }));
    }
    return images.get(key);
  };
  const names = new Set<string>(json.nodes.map((n: any) => n.name as string).filter((n: string) => n.startsWith('mat_')));
  for (const m of json.materials as any[]) {
    if (!names.has('mat_' + m.name)) continue;
    const base = tex(m.pbrMetallicRoughness?.baseColorTexture?.index, true);
    if (!base) continue;
    const [map, normalMap, emissiveMap] = await Promise.all([base, tex(m.normalTexture?.index, false), tex(m.emissiveTexture?.index, true)]);
    const set: TexSet = { map, normalMap, emissiveMap };
    if (emissiveMap) set.emissive = new THREE.Color().fromArray(m.emissiveFactor ?? [1, 1, 1]);
    registry.set(m.name, set);
  }
  for (const b of bindings) if (registry.has(b.name)) apply(b);
}

function place(t: THREE.Texture, repeat: [number, number], old?: THREE.Texture | null): THREE.Texture {
  const c = t.clone();
  c.repeat.set(repeat[0], repeat[1]);
  c.wrapS = c.wrapT = THREE.RepeatWrapping;
  c.anisotropy = 4;
  c.needsUpdate = true;
  old?.dispose();
  return c;
}
function apply(b: Binding) {
  const set = registry.get(b.name);
  if (!set) return;
  b.mat.map = place(set.map, b.repeat, b.mat.map);
  if (set.normalMap) {
    b.mat.normalMap = place(set.normalMap, b.repeat, b.mat.normalMap);
    b.mat.normalScale.set(b.normalScale, b.normalScale);
  }
  if (set.emissiveMap) {
    b.mat.emissiveMap = place(set.emissiveMap, b.repeat, b.mat.emissiveMap);
    b.mat.emissive = set.emissive!.clone();
    b.mat.emissiveIntensity = b.glow;
  }
  b.mat.needsUpdate = true;
}

export interface Pack {
  /** The pack's meshes by node name (`rim`, `prop_horn_0`, ...), in game units; the scene is not added anywhere. */
  nodes: Map<string, THREE.Mesh>;
  credits: unknown;
}
const packs = new Map<string, Promise<Pack | null>>();

/** Fetch a pack once (kit, or an arena's); resolves null when it cannot be loaded, so callers keep their fallback. */
export function loadPack(url: string): Promise<Pack | null> {
  let p = packs.get(url);
  if (!p) {
    p = fetchModel(url)
      .then(async (buf) => {
        await registerMaterials(buf);
        const gltf: any = await new Promise((res, rej) => new GLTFLoader().parse(buf.slice(0), '', res, rej));
        const nodes = new Map<string, THREE.Mesh>();
        gltf.scene.updateMatrixWorld(true);
        gltf.scene.traverse((o: THREE.Object3D) => {
          if (o instanceof THREE.Mesh && !o.name.startsWith('mat_')) nodes.set(o.name, o);
        });
        return { nodes, credits: gltf.parser?.json?.asset?.extras?.credits } as Pack;
      })
      .catch((e) => {
        console.warn(`arena pack ${url} failed to load, keeping the built-in look`, e);
        return null;
      });
    packs.set(url, p);
  }
  return p;
}

/** Forget cached packs (tests). */
export function forgetPacks() {
  packs.clear();
  registry.clear();
}

export function kitLoaded(): boolean {
  return registry.has('sand');
}

export interface MatOpts {
  /** Tiles across/down the surface (world size / tile size). */
  repeat?: [number, number];
  color?: number;
  roughness?: number;
  metalness?: number;
  normalScale?: number;
  /** Glow (emissive map strength) for materials that have a glow map (lava). */
  glow?: number;
  side?: THREE.Side;
  flatShading?: boolean;
  transparent?: boolean;
  opacity?: number;
}

/** A standard material using a named kit texture: the canvas stand-in first, the real maps once the pack is in. */
export function kitMaterial(name: string, o: MatOpts = {}): THREE.MeshStandardMaterial {
  const repeat = o.repeat ?? [1, 1];
  const mat = new THREE.MeshStandardMaterial({
    map: fallbackTexture(name),
    color: o.color ?? 0xffffff,
    roughness: o.roughness ?? 0.9,
    metalness: o.metalness ?? 0,
    side: o.side ?? THREE.FrontSide,
    flatShading: o.flatShading ?? false,
    transparent: o.transparent ?? false,
    opacity: o.opacity ?? 1,
  });
  mat.map!.repeat.set(repeat[0], repeat[1]);
  mat.map!.wrapS = mat.map!.wrapT = THREE.RepeatWrapping;
  const b: Binding = { mat, name, repeat, normalScale: o.normalScale ?? 1, glow: o.glow ?? 1 };
  bindings.add(b);
  mat.userData.binding = b;
  if (registry.has(name)) apply(b);
  return mat;
}

/** Free a kit material's own texture clones and stop tracking it (the shared images stay with the pack). */
export function releaseKitMaterial(mat: THREE.Material) {
  const b = mat.userData?.binding as Binding | undefined;
  if (!b) return false;
  bindings.delete(b);
  const m = mat as THREE.MeshStandardMaterial;
  m.map?.dispose();
  m.normalMap?.dispose();
  m.emissiveMap?.dispose();
  m.dispose();
  return true;
}

// ------------------------------------------------------------------ geometry helpers

/** A box whose UVs follow world size: `tile` yards per texture repeat, so bricks look the same on every wall. */
export function worldBox(w: number, h: number, d: number, tile = 4, tileY = tile): THREE.BoxGeometry {
  const g = new THREE.BoxGeometry(w, h, d);
  const uv = g.attributes.uv as THREE.BufferAttribute;
  // BoxGeometry face order: +x, -x, +y, -y, +z, -z; 4 vertices each
  const faces: [number, number][] = [[d, h], [d, h], [w, d], [w, d], [w, h], [w, h]];
  for (let f = 0; f < 6; f++)
    for (let v = 0; v < 4; v++) {
      const i = f * 4 + v;
      const [a, b] = faces[f];
      uv.setXY(i, (uv.getX(i) * a) / tile, (uv.getY(i) * b) / (f === 2 || f === 3 ? tile : tileY));
    }
  return g;
}

/** A chunky rock: an icosahedron pushed about by noise, flat-shaded. */
export function rockGeometry(r: number, seed: number, squash = 0.7): THREE.BufferGeometry {
  const g = new THREE.IcosahedronGeometry(r, 1);
  const rnd = rng(seed);
  const p = g.attributes.position;
  const k = new Map<string, number>();
  for (let i = 0; i < p.count; i++) {
    const key = `${p.getX(i).toFixed(3)},${p.getY(i).toFixed(3)},${p.getZ(i).toFixed(3)}`;
    if (!k.has(key)) k.set(key, 0.72 + rnd() * 0.5);
    const s = k.get(key)!;
    p.setXYZ(i, p.getX(i) * s, p.getY(i) * s * squash, p.getZ(i) * s);
  }
  g.computeVertexNormals();
  return g;
}

/** Cover keeps its exact collision footprint up to this height (yards); a taper, flare or lean only starts above it. */
export const COVER_FLAT = 2.6;

/**
 * A shaft of circumradius r that stays exactly r up to COVER_FLAT (a ring of vertices sits right at that height, so nothing
 * is cut off between rings) and tapers linearly to `top * r` at height h; origin at the foot, UVs like a cylinder's.
 */
export function taperedShaft(r: number, h: number, sides: number, top: number, segs = 8): THREE.BufferGeometry {
  const ys = [0, COVER_FLAT / 2, COVER_FLAT];
  for (let i = 1; i <= segs; i++) ys.push(COVER_FLAT + ((h - COVER_FLAT) * i) / segs);
  const pos: number[] = [], uv: number[] = [], idx: number[] = [];
  for (const y of ys) {
    const k = 1 - (1 - top) * Math.min(1, Math.max(0, (y - COVER_FLAT) / Math.max(1e-6, h - COVER_FLAT)));
    for (let i = 0; i <= sides; i++) {
      const a = (i / sides) * Math.PI * 2;
      pos.push(Math.sin(a) * r * k, y, Math.cos(a) * r * k);
      uv.push(i / sides, y / h);
    }
  }
  const row = sides + 1;
  for (let j = 0; j < ys.length - 1; j++)
    for (let i = 0; i < sides; i++) {
      const a = j * row + i, b = a + row, c = b + 1, d = a + 1;
      idx.push(a, d, b, b, d, c);
    }
  const centre = pos.length / 3; // a cap on top so the tip is closed
  pos.push(0, h, 0);
  uv.push(0.5, 1);
  const last = (ys.length - 1) * row;
  for (let i = 0; i < sides; i++) idx.push(centre, last + i, last + i + 1);
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2));
  g.setIndex(idx);
  g.computeVertexNormals();
  return g;
}

/**
 * A faceted spire, a little crooked, with a jagged broken top; origin at its foot. Up to COVER_FLAT it is a plain prism of
 * circumradius r (what blocks you is a circle of radius r, so what you see there must be the same); the taper to a point,
 * the lean and the jitter all start above that.
 */
export function spireGeometry(r: number, h: number, seed: number, sides = 12, lean = 0.12): THREE.BufferGeometry {
  const rnd = rng(seed);
  const g = taperedShaft(r, h, sides, 0.07, 8);
  const p = g.attributes.position;
  const ang = rnd() * Math.PI * 2;
  const jit = new Map<string, number>();
  for (let i = 0; i < p.count; i++) {
    const y = p.getY(i);
    const u = Math.min(1, Math.max(0, (y - COVER_FLAT) / Math.max(1e-6, h - COVER_FLAT)));
    const side = Math.round(((Math.atan2(p.getX(i), p.getZ(i)) + Math.PI * 2) % (Math.PI * 2)) / (Math.PI * 2) * sides) % sides;
    const key = `${y.toFixed(3)}/${side}`;
    if (!jit.has(key)) jit.set(key, rnd());
    const j = 1 + (jit.get(key)! - 0.5) * 0.18 * u;
    p.setX(i, p.getX(i) * j + Math.cos(ang) * lean * h * u * u);
    p.setZ(i, p.getZ(i) * j + Math.sin(ang) * lean * h * u * u);
  }
  g.computeVertexNormals();
  return g;
}

/** A wall or barricade body with a jagged, broken top (a box whose top vertices are lifted by noise). */
export function jaggedBox(w: number, h: number, d: number, seed: number, jag = 0.25, tile = 4): THREE.BufferGeometry {
  const sx = Math.max(1, Math.round(w / 1.2)), sz = Math.max(1, Math.round(d / 1.2));
  const g = new THREE.BoxGeometry(w, h, d, sx, 1, sz);
  const rnd = rng(seed);
  const p = g.attributes.position;
  const top = new Map<string, number>();
  for (let i = 0; i < p.count; i++) {
    if (p.getY(i) < h / 2 - 1e-6) continue;
    const key = `${p.getX(i).toFixed(3)},${p.getZ(i).toFixed(3)}`;
    if (!top.has(key)) top.set(key, (rnd() - 0.6) * jag * h);
    p.setY(i, h / 2 + top.get(key)!);
  }
  const uv = g.attributes.uv as THREE.BufferAttribute;
  for (let i = 0; i < uv.count; i++) uv.setXY(i, (uv.getX(i) * Math.max(w, d)) / tile, (uv.getY(i) * h) / tile);
  g.computeVertexNormals();
  return g;
}

/** A cluster of crystal prisms leaning out of a common foot (ice and cinder crystals); origin at the foot. */
export function crystalCluster(r: number, h: number, seed: number, n = 5): THREE.BufferGeometry {
  const rnd = rng(seed);
  const parts: THREE.BufferGeometry[] = [];
  for (let i = 0; i < n; i++) {
    const big = i === 0;
    const hh = big ? h : h * (0.3 + rnd() * 0.4);
    const rr = big ? r * 0.55 : r * (0.18 + rnd() * 0.2);
    const g = new THREE.ConeGeometry(rr, hh, 6, 1);
    g.translate(0, hh / 2, 0);
    const a = big ? 0 : rnd() * Math.PI * 2;
    const lean = big ? 0.05 : 0.25 + rnd() * 0.35;
    g.rotateZ(-lean);
    g.rotateY(a);
    g.translate(big ? 0 : Math.cos(a) * r * 0.5, 0, big ? 0 : Math.sin(a) * r * 0.5);
    parts.push(g);
  }
  return mergeGeometries(parts);
}

/** Merge non-indexed copies of geometries (positions, normals, uvs) into one. */
export function mergeGeometries(list: THREE.BufferGeometry[]): THREE.BufferGeometry {
  const pos: number[] = [], nrm: number[] = [], uv: number[] = [];
  for (const g0 of list) {
    const g = g0.index ? g0.toNonIndexed() : g0;
    for (const v of g.attributes.position.array) pos.push(v);
    for (const v of g.attributes.normal.array) nrm.push(v);
    if (g.attributes.uv) for (const v of g.attributes.uv.array) uv.push(v);
    else for (let i = 0; i < g.attributes.position.count * 2; i++) uv.push(0);
  }
  const out = new THREE.BufferGeometry();
  out.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  out.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3));
  out.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2));
  return out;
}

// ------------------------------------------------------------------ terrain: noise, the ring around the arena, horns, sky

const hash2 = (ix: number, iz: number, seed: number) => {
  let h = Math.imul(ix, 374761393) ^ Math.imul(iz, 668265263) ^ Math.imul(seed + 1, 1013904223);
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
};
/** Smooth 2D value noise (0..1). */
export function noise2(x: number, z: number, seed = 0): number {
  const ix = Math.floor(x), iz = Math.floor(z);
  const fx = x - ix, fz = z - iz;
  const sx = fx * fx * (3 - 2 * fx), sz = fz * fz * (3 - 2 * fz);
  const a = hash2(ix, iz, seed), b = hash2(ix + 1, iz, seed), c = hash2(ix, iz + 1, seed), d = hash2(ix + 1, iz + 1, seed);
  return (a * (1 - sx) + b * sx) * (1 - sz) + (c * (1 - sx) + d * sx) * sz;
}
export function fbm2(x: number, z: number, seed = 0, octaves = 4): number {
  let v = 0, amp = 1, tot = 0, f = 1;
  for (let o = 0; o < octaves; o++) {
    v += noise2(x * f, z * f, seed + o * 31) * amp;
    tot += amp;
    amp *= 0.5;
    f *= 2.03;
  }
  return v / tot;
}
export const smoothstep = (a: number, b: number, x: number) => {
  const t = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
};

export interface RingOpts {
  /** Centre and half extents of the inner rounded rectangle (the outer face of the rampart). */
  cx: number;
  cz: number;
  hx: number;
  hz: number;
  corner?: number;
  /** Distances outward from that rectangle, one ring each (ascending). */
  dist: number[];
  samples?: number;
  height(x: number, z: number, d: number): number;
  /** Vertex colour (the glow factor of the material reads its green channel). */
  color(x: number, z: number, d: number, h: number): [number, number, number];
  /** Yards per texture repeat (planar UVs). */
  tile: number;
}

/**
 * One continuous skin of terrain around a rectangle: rings of rounded-rectangle offset curves, each lifted by a height
 * function, so the crater wall, cliffs, plain and shore of a map are a single welded mesh (no loose chunks).
 */
export function ringTerrain(o: RingOpts): THREE.BufferGeometry {
  const r0 = o.corner ?? 3;
  const ax = o.hx - r0, az = o.hz - r0;
  const arc = (Math.PI / 2) * r0;
  const lens = [2 * az, arc, 2 * ax, arc, 2 * az, arc, 2 * ax, arc];
  const total = lens.reduce((a, b) => a + b, 0);
  const N = o.samples ?? 360;
  // base points and outward normals, evenly spaced along the perimeter (start at +x side, walking towards +z)
  const base: { x: number; z: number; nx: number; nz: number }[] = [];
  for (let i = 0; i < N; i++) {
    let u = (i / N) * total, k = 0;
    while (u > lens[k]) u -= lens[k++];
    const f = u / lens[k];
    let x: number, z: number, nx: number, nz: number;
    if (k % 2 === 0) {
      const side = k / 2; // 0 +x, 1 +z, 2 -x, 3 -z
      if (side === 0) { x = o.hx; z = -az + f * 2 * az; nx = 1; nz = 0; }
      else if (side === 1) { x = ax - f * 2 * ax; z = o.hz; nx = 0; nz = 1; }
      else if (side === 2) { x = -o.hx; z = az - f * 2 * az; nx = -1; nz = 0; }
      else { x = -ax + f * 2 * ax; z = -o.hz; nx = 0; nz = -1; }
    } else {
      const corner = (k - 1) / 2; // 0: +x+z ... walking order
      const cxs = [ax, -ax, -ax, ax][corner], czs = [az, az, -az, -az][corner];
      const a0 = [0, Math.PI / 2, Math.PI, Math.PI * 1.5][corner];
      const a = a0 + f * (Math.PI / 2);
      nx = Math.cos(a); nz = Math.sin(a);
      x = cxs + nx * r0; z = czs + nz * r0;
    }
    base.push({ x: o.cx + x, z: o.cz + z, nx, nz });
  }
  const M = o.dist.length;
  const pos = new Float32Array(N * M * 3), col = new Float32Array(N * M * 3), uv = new Float32Array(N * M * 2);
  for (let m = 0; m < M; m++)
    for (let i = 0; i < N; i++) {
      const b = base[i], d = o.dist[m];
      const x = b.x + b.nx * d, z = b.z + b.nz * d;
      const h = o.height(x, z, d);
      const v = m * N + i;
      pos.set([x, h, z], v * 3);
      col.set(o.color(x, z, d, h), v * 3);
      uv.set([x / o.tile, z / o.tile], v * 2);
    }
  const idx: number[] = [];
  for (let m = 0; m < M - 1; m++)
    for (let i = 0; i < N; i++) {
      const a = m * N + i, b = m * N + ((i + 1) % N), c = (m + 1) * N + i, d = (m + 1) * N + ((i + 1) % N);
      idx.push(a, b, c, b, d, c);
    }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  g.setAttribute('color', new THREE.BufferAttribute(col, 3));
  g.setAttribute('uv', new THREE.BufferAttribute(uv, 2));
  g.setIndex(idx);
  g.computeVertexNormals();
  return g;
}

/**
 * A crooked obsidian horn: a tapering, ridged, curved shaft, UVs in yards (no stretching); origin at the foot. Up to
 * COVER_FLAT it is a round shaft of radius r (the ridges only cut inward, at most 0.03); the taper, the ridges' full depth
 * and the bend all start above that, so the footprint you see is the circle that blocks you.
 */
export function hornGeometry(r: number, h: number, seed: number, tile = 3.5): THREE.BufferGeometry {
  const rnd = rng(seed);
  const SIDES = 16, RINGS = 28;
  const ang = rnd() * Math.PI * 2, bend = 0.1 + rnd() * 0.12, wob = rnd() * 6;
  const ph = [rnd() * 6.28, rnd() * 6.28, rnd() * 6.28];
  const pos: number[] = [], col: number[] = [], uv: number[] = [], idx: number[] = [];
  const flat = COVER_FLAT / h;
  for (let j = 0; j <= RINGS; j++) {
    // rings are packed low so the flat part has a few of its own
    const t = (j / RINGS) ** 1.5;
    const y = t * h;
    const u = Math.max(0, (t - flat) / (1 - flat)); // 0 up to the flat height, then 0..1 to the tip
    const cxo = Math.cos(ang) * bend * h * u * u + Math.sin(u * 5 + wob) * 0.05 * r * u;
    const czo = Math.sin(ang) * bend * h * u * u + Math.cos(u * 4 + wob) * 0.05 * r * u;
    const rad = Math.max(0.015 * r, r * Math.pow(1 - u, 0.9) * (1 - 0.08 * u * (0.5 - 0.5 * Math.sin(u * 9 + wob))));
    const depth = 0.03 / r + (0.31 - 0.03 / r) * Math.min(1, u * 4); // how deep the ridges cut (a fraction of the radius)
    for (let i = 0; i <= SIDES; i++) {
      const a = (i / SIDES) * Math.PI * 2;
      const ridge = (Math.sin(a * 3 + ph[0] + t * 2.2) * 0.52 + Math.sin(a * 5 + ph[1] - t * 3) * 0.32 + Math.sin(a * 8 + ph[2]) * 0.16) * 0.5 + 0.5; // 0..1
      const rr = rad * (1 - depth * (1 - ridge));
      pos.push(cxo + Math.cos(a) * rr, y, czo + Math.sin(a) * rr);
      uv.push((i / SIDES) * ((r * 2 * Math.PI) / tile), (y * 1.15) / tile);
      // dark glassy shaft, an ember glow low on it (the green channel drives the glow of materials that have one)
      const glow = Math.exp(-t * 9) * (0.6 + 0.4 * Math.sin(a * 4 + ph[0]));
      col.push(0.7 + glow * 0.3, 0.12 + glow * 0.9, 0.12 + glow * 0.8);
    }
  }
  for (let j = 0; j < RINGS; j++)
    for (let i = 0; i < SIDES; i++) {
      const a = j * (SIDES + 1) + i, b = a + 1, c = a + SIDES + 1, d = c + 1;
      idx.push(a, c, b, b, c, d);
    }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('color', new THREE.Float32BufferAttribute(col, 3));
  g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2));
  g.setIndex(idx);
  g.computeVertexNormals();
  return g;
}

/** Let a material's emissive follow the vertex colour's green channel (lava glows in the low, hot parts and fades up the rock; the diffuse colour is tinted by it too, so give such a material a dark base). */
export function emissiveFromVertexColor(mat: THREE.MeshStandardMaterial) {
  mat.vertexColors = true;
  mat.onBeforeCompile = (sh) => {
    sh.fragmentShader = sh.fragmentShader.replace('#include <emissivemap_fragment>', '#include <emissivemap_fragment>\n  totalEmissiveRadiance *= vColor.g;');
  };
  mat.customProgramCacheKey = () => 'emissiveVC';
}

/** A sky dome (gradient by elevation, so the horizon glow sits at the horizon); stops run zenith 0 .. horizon 0.5 .. nadir 1. */
export function skyDome(stops: [number, string][]): THREE.Mesh {
  const tex = canvasTex(8, 512, (g) => {
    const grad = g.createLinearGradient(0, 0, 0, 512);
    for (const [at, color] of stops) grad.addColorStop(at, color);
    g.fillStyle = grad;
    g.fillRect(0, 0, 8, 512);
  });
  const m = new THREE.Mesh(new THREE.SphereGeometry(640, 32, 24), new THREE.MeshBasicMaterial({ map: tex, side: THREE.BackSide, fog: false, depthWrite: false, depthTest: false }));
  m.renderOrder = -1000;
  m.frustumCulled = false;
  return m;
}

/**
 * Many boxes baked into two geometries (carved sides, plain caps), so a barricade of fifty blocks costs two draw calls.
 * `side` boxes follow BoxGeometry's face order for materials [side, side, cap, cap, side, side]; `cap` boxes are all cap.
 */
export class BoxBatch {
  private sides = { p: [] as number[], n: [] as number[], u: [] as number[] };
  private caps = { p: [] as number[], n: [] as number[], u: [] as number[] };
  add(w: number, h: number, d: number, x: number, y: number, z: number, kind: 'side' | 'cap' = 'side') {
    const g = new THREE.BoxGeometry(w, h, d);
    const P = g.attributes.position, N = g.attributes.normal, U = g.attributes.uv, I = g.index!;
    for (const grp of g.groups) {
      const dst = kind === 'cap' || grp.materialIndex === 2 || grp.materialIndex === 3 ? this.caps : this.sides;
      for (let k = grp.start; k < grp.start + grp.count; k++) {
        const v = I.getX(k);
        dst.p.push(P.getX(v) + x, P.getY(v) + y, P.getZ(v) + z);
        dst.n.push(N.getX(v), N.getY(v), N.getZ(v));
        dst.u.push(U.getX(v), U.getY(v));
      }
    }
    g.dispose();
  }
  build(): { sides: THREE.BufferGeometry | null; caps: THREE.BufferGeometry | null } {
    const make = (a: { p: number[]; n: number[]; u: number[] }) => {
      if (!a.p.length) return null;
      const g = new THREE.BufferGeometry();
      g.setAttribute('position', new THREE.Float32BufferAttribute(a.p, 3));
      g.setAttribute('normal', new THREE.Float32BufferAttribute(a.n, 3));
      g.setAttribute('uv', new THREE.Float32BufferAttribute(a.u, 2));
      return g;
    };
    return { sides: make(this.sides), caps: make(this.caps) };
  }
}

/** The first mesh of a pack piece, cloned with its own geometry reference (shared across arenas, never disposed by them). */
export function pieceMesh(pack: Pack | null, name: string): THREE.Mesh | null {
  const m = pack?.nodes.get(name);
  if (!m) return null;
  const out = new THREE.Mesh(m.geometry, m.material);
  out.name = name;
  return out;
}
