#!/usr/bin/env node
// Arena pipeline: the three downloaded scenes (Sketchfab "HELL ARENA", "Hell arena", "Arena") -> the game's arena packs.
//   node scripts/prep-arena.mjs --hell1 <hell_arena_1.glb> --hell2 <hell_arena.glb> --arena <arena.glb> [--only kit|cinder|forge|sandstone] [--out dir] [--preview dir]
// Run `npx tsx scripts/pack-models.ts` afterwards (model files are only served as .pak; the plain GLBs move to git-ignored assets-src/models).
// The originals are NOT kept in the repo. Credits live in each output's asset.extras (and client/src/credits.ts, CREDITS.md).
//
// OUTPUT (client/public/models/arenas/*.glb, loaded lazily by client/src/arenaModels.ts and arenaKit.ts)
//   kit.glb       shared tiling materials, one tiny swatch mesh per material named `mat_<name>` (map, normal map, optional emissive map):
//                 from the "Arena" scene: sand, sandbrick, cobble, carved (shield block face), sandstone, obeliskstone;
//                 generated here (scripts/lib/texgen.mjs, seamless, 1024 px): snow, ice, frostbrick, mossbrick, flagstone, planks, dirt.
//   cinder.glb    the hell textures as `mat_*` swatches (cracked lava rock with a glow map, basalt, lava flow); the crater wall, plain and
//                 horns are generated by the client.
//   forge.glb     the grate disc `grate` and the hell textures as `mat_*`; the lava moat and cliffs are generated by the client.
//   sandstone.glb the "Arena" stadium shell (arched walls, towers, gates, rims; ad boards, sky boxes, leopard-print roof lights and
//                 the middle floor dropped), scaled 0.7 so the walls stand about 40 yards out, the obelisks as unit-height `prop_obelisk_N`.
// Every node is in game units: Y up, feet at y = 0, the arena centred on the origin.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Pack } from './lib/pack.mjs';
import { encodePng } from './lib/png.mjs';
import { addDetail, addGrain, bricks, frostDust, ground, heightFromRgba, ice, makeSeamless, normalMap, planks, sharpen, slabs, overlay, toRgba } from './lib/texgen.mjs';
import { bbox, components, imageByIndex, loadScene, materialImage, recomputeNormals, sized, transform, triCount } from './lib/scene.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const flag = (n) => {
  const i = args.indexOf(n);
  return i < 0 ? null : args[i + 1];
};
const out = resolve(flag('--out') || join(here, '../client/public/models/arenas'));
const preview = flag('--preview');
const only = flag('--only');
const want = (n) => !only || only === n;
mkdirSync(out, { recursive: true });
if (preview) mkdirSync(preview, { recursive: true });

const CREDIT = {
  hell1: { title: 'HELL ARENA', author: '3DMAN (https://sketchfab.com/3dmanx888)', license: 'CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)', source: 'https://sketchfab.com/3d-models/hell-arena-9db7838c98ab4ae5a6a783dda03115eb' },
  hell2: { title: 'Hell arena', author: '3DMAN (https://sketchfab.com/3dmanx888)', license: 'CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)', source: 'https://sketchfab.com/3d-models/hell-arena-14b8a6e3cba342f5a952ca5488180489' },
  arena: { title: 'Arena', author: 'lombardirowchik (https://sketchfab.com/lombardirowchik)', license: 'CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)', source: 'https://sketchfab.com/3d-models/arena-0f990d29a01f4ef5b2c5013797ea32fc' },
};
/** Checked against the source files' own metadata so a wrong download is caught. */
function check(sc, key) {
  const e = sc.json.asset.extras || {};
  if (e.title !== CREDIT[key].title || e.author !== CREDIT[key].author || e.source !== CREDIT[key].source) throw new Error(`${key}: the file's own metadata does not match the credit (${JSON.stringify(e)})`);
}
const extras = (...keys) => ({ credits: keys.map((k) => CREDIT[k]), note: 'Re-scaled, re-oriented, decimated and re-textured for the game (scripts/prep-arena.mjs).' });

const save = (name, pack) => {
  const bytes = pack.build();
  writeFileSync(join(out, name), bytes);
  console.log(`${name}: ${(bytes.length / 1024 / 1024).toFixed(2)} MB (${(pack.bytesImages / 1024 / 1024).toFixed(2)} MB textures), ${pack.meshes.length} nodes`);
};
const savePng = (name, rgba, w, h) => preview && writeFileSync(join(preview, name + '.png'), encodePng(rgba, w, h));
const triTotal = (list) => list.reduce((a, p) => a + triCount(p), 0);

/** Add a tiling material from an RGBA image (+ a normal map made from its luminance or a height field). */
function tiling(pack, name, base, { height, strength = 3, normalSize = 512, roughness = 0.9, quality = 80, emissive, emissiveFactor } = {}) {
  const hgt = height ?? heightFromRgba(base.rgba, base.w, base.h);
  const nm = normalMap(hgt, base.w, base.h, strength);
  const small = normalSize === base.w ? { rgba: nm, w: base.w, h: base.h } : sized({ data: nm, width: base.w, height: base.h }, normalSize);
  pack.material(name, { base, normal: small, roughness, quality, emissive, emissiveFactor });
  pack.swatch('mat_' + name, name);
  savePng(name, base.rgba, base.w, base.h);
  savePng(name + '.n', small.rgba, small.w, small.h);
}
const fromTex = (t) => ({ rgba: toRgba(t), w: t.w, h: t.h });
/** A small photo texture as a crisp, seamless 1024 px tile: enlarged, made seamless, unsharp-masked, given a generated detail layer (other scale than the photo's own) and grain. */
function photo(img, size = 1024, grain = 0.1, seamless = true, seed = 3, crop, { sharp = 1.1, detail = 0.08 } = {}) {
  if (crop) {
    // cut a border away (the source tiles carry grass fringes and edge bands)
    const [x0, y0, x1, y1] = crop.map((v, i) => Math.round(v * (i % 2 ? img.height : img.width)));
    const w = x1 - x0, h = y1 - y0, d = new Uint8Array(w * h * 4);
    for (let y = 0; y < h; y++) d.set(img.data.subarray(((y0 + y) * img.width + x0) * 4, ((y0 + y) * img.width + x0 + w) * 4), y * w * 4);
    img = { data: d, width: w, height: h };
  }
  let r = sized(img, size);
  if (seamless) r.rgba = makeSeamless(r.rgba, size, size);
  if (sharp) sharpen(r.rgba, size, size, { amount: sharp, radius: 2 });
  if (detail) addDetail(r.rgba, size, size, { amount: detail, seed: seed + 40, scale: 36 });
  addGrain(r.rgba, size, size, grain, seed);
  return r;
}
const uvUnit = (p) => ({ pos: p.pos, nrm: p.nrm, uv: p.uv, idx: p.idx });
/** Move a piece so its base centre is the origin and scale it to height 1 (client scales it to the cover's size). */
function unitHeight(p) {
  const b = bbox(p);
  let sx = 0, sz = 0, n = 0;
  for (let i = 0; i < p.pos.length; i += 3) if (p.pos[i + 1] < b.min[1] + b.size[1] * 0.12) { sx += p.pos[i]; sz += p.pos[i + 2]; n++; }
  sx /= n; sz /= n;
  const k = 1 / b.size[1];
  return transform(p, ([x, y, z]) => [(x - sx) * k, (y - b.min[1]) * k, (z - sz) * k]);
}

// ---------------------------------------------------------------- kit
async function buildKit() {
  const sc = loadScene(flag('--arena'));
  check(sc, 'arena');
  const pack = new Pack(extras('arena'));
  const img = (i) => imageByIndex(sc, i);
  // from the Arena scene (indices are the file's image numbers)
  tiling(pack, 'sand', photo(img(11), 1024, 0.14, true, 3, undefined, { sharp: 1.6, detail: 0.1 }), { strength: 2.4, roughness: 1 });
  tiling(pack, 'sandbrick', photo(img(13), 1024, 0.08, true, 3, [0, 0.14, 1, 0.86], { sharp: 1.4, detail: 0.08 }), { strength: 4 });
  tiling(pack, 'cobble', photo(img(22), 1024, 0.1, true, 3, [0, 0.2, 1, 1], { sharp: 1.6, detail: 0.1 }), { strength: 4.5 });
  tiling(pack, 'carved', photo(img(44), 1024, 0.05, false, 3, [0, 0.13, 1, 1], { sharp: 1.4, detail: 0.06 }), { strength: 5 });
  tiling(pack, 'sandstone', photo(img(43), 1024, 0.12, true, 3, undefined, { sharp: 2, detail: 0.14 }), { strength: 3 });
  tiling(pack, 'obeliskstone', photo(img(26), 1024, 0.08, true, 3, undefined, { sharp: 1.7, detail: 0.1 }), { strength: 3.5 });
  // generated, 1024 px
  const S = 1024;
  const snow = ground(S, S, { colors: ['#b4c4d9', '#f2f7ff'], seed: 21, fine: 0.1 });
  tiling(pack, 'snow', fromTex(snow), { height: snow.height, strength: 3, roughness: 0.75 });
  const ic = ice(S, S, { seed: 22 });
  tiling(pack, 'ice', fromTex(ic), { height: ic.height, strength: 4, roughness: 0.25 });
  const fb = bricks(S, S, { rows: 6, cols: 3, colors: ['#7f97b8', '#b4c9e2'], mortarColor: '#2d3a4e', seed: 23, grain: 0.1, variation: 0.1 });
  frostDust(fb, { color: '#eef5ff', amount: 0.5, seed: 24 });
  tiling(pack, 'frostbrick', fromTex(fb), { height: fb.height, strength: 4 });
  const mb = bricks(S, S, { rows: 7, cols: 3, colors: ['#7b7768', '#a8a28c'], mortarColor: '#34322a', seed: 31, grain: 0.16 });
  overlay(mb, { color: '#566f38', amount: 0.3, seed: 32, scale: 7, specks: 0.5 });
  tiling(pack, 'mossbrick', fromTex(mb), { height: mb.height, strength: 4 });
  const fl = slabs(S, S, { cells: 6, colors: ['#686c5f', '#979d86'], mortarColor: '#2f3129', seed: 41 });
  overlay(fl, { color: '#566f38', amount: 0.26, seed: 42, scale: 8, specks: 0.5 });
  tiling(pack, 'flagstone', fromTex(fl), { height: fl.height, strength: 4 });
  const pl = planks(S, S, { boards: 8, seed: 51 });
  tiling(pack, 'planks', fromTex(pl), { height: pl.height, strength: 3 });
  const dt = ground(S, S, { colors: ['#6d5a40', '#a08560'], seed: 61, pebbles: 40, fine: 0.2, ridge: 0.4 });
  tiling(pack, 'dirt', fromTex(dt), { height: dt.height, strength: 4, roughness: 1 });
  save('kit.glb', pack);
}

// ---------------------------------------------------------------- hell textures (Hell arena scene) shared by cinder and forge
function hellTextures(pack, sc2, names) {
  const img = (i) => imageByIndex(sc2, i);
  const crack = photo(img(0), 1024, 0.04);
  if (names.includes('lavacrack')) tiling(pack, 'lavacrack', crack, { strength: 3, roughness: 0.85, emissive: crack, emissiveFactor: [1.6, 1.25, 1.0], quality: 82 });
  if (names.includes('basalt')) tiling(pack, 'basalt', photo(img(2), 1024, 0.05), { strength: 5, roughness: 0.9 });
  if (names.includes('basaltdark')) tiling(pack, 'basaltdark', photo(img(4), 1024, 0.05), { strength: 3, roughness: 0.95 });
  if (names.includes('blackbrick')) tiling(pack, 'blackbrick', photo(img(8), 1024, 0.05), { strength: 4, roughness: 0.85 });
  if (names.includes('greybrick')) tiling(pack, 'greybrick', photo(img(3), 1024, 0.05), { strength: 5, roughness: 0.9 });
  if (names.includes('orangerock')) tiling(pack, 'orangerock', photo(img(7), 1024, 0.06), { strength: 3, roughness: 1 });
  const flow = photo(img(5), 1024, 0.0);
  if (names.includes('lavaflow')) tiling(pack, 'lavaflow', flow, { strength: 2, roughness: 0.4, emissive: flow, emissiveFactor: [1.3, 1.0, 0.8], quality: 82 });
}

// ---------------------------------------------------------------- cinder
// The crater, its wall, the plain and the horns are generated by the client (arenaMap.ts: one welded terrain skin, so nothing floats);
// the scanned scene contributes its textures (cracked lava rock with a glow map, basalt, lava flow).
async function buildCinder() {
  const sc1 = loadScene(flag('--hell1'));
  const sc2 = loadScene(flag('--hell2'));
  check(sc1, 'hell1');
  check(sc2, 'hell2');
  const pack = new Pack(extras('hell1', 'hell2'));
  hellTextures(pack, sc2, ['lavacrack', 'basalt', 'basaltdark', 'lavaflow']);
  save('cinder.glb', pack);
}

// ---------------------------------------------------------------- forge
// Floor and wall textures from the "Hell arena" scene, plus its grate disc; the moat and cliffs are generated by the client.
async function buildForge() {
  const sc2 = loadScene(flag('--hell2'));
  check(sc2, 'hell2');
  const pack = new Pack(extras('hell2'));
  const mat = (i, slot) => materialImage(sc2, i, slot);
  pack.material('grate', { base: sized(mat(3, 'base'), 512), roughness: 0.6, metalness: 0.4 });
  const grate = transform(sc2.pieces.find((p) => p.name === 'Object_8'), ([x, y, z]) => [x * 1.55, (y - 0.69) * 1.55, z * 1.55]);
  pack.mesh('grate', uvUnit(grate), 'grate');
  hellTextures(pack, sc2, ['lavaflow', 'greybrick', 'blackbrick', 'basalt']);
  console.log('forge grate', triCount(grate));
  save('forge.glb', pack);
}

// ---------------------------------------------------------------- sandstone
async function buildSandstone() {
  const sc = loadScene(flag('--arena'));
  check(sc, 'arena');
  const pack = new Pack(extras('arena'));
  const S = 0.7 / 100; // the scene is in centimetres-ish (stadium about 14000 across): 0.7 yard per 100 units
  // meshes dropped: ad boards (3..12), sky box and sky faces (13, 51..56), the white cube (2), leopard-print roof lights (48, 49),
  // the picture ring (50), the middle floors and decals (14, 15, 17, 18, 23)
  const dropped = new Set([2, 3, 20, 24, 30, 31, 32, 34, 35, 45, 46, 47, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 23, 48, 49, 50, 51, 52, 53, 54, 55, 56]);
  const parts = sc.pieces.filter((p) => !dropped.has(+p.name.replace(/\D/g, '')));
  const obelisk = sc.pieces.find((p) => p.name === 'Object_30');
  const used = new Map();
  let tris = 0;
  for (const p of parts) {
    const key = p.material;
    let name = 'm' + key;
    if (!used.has(key)) {
      const im = materialImage(sc, key, 'base');
      if (!im) continue;
      const size = Math.min(512, Math.max(64, im.width));
      pack.material(name, { base: sized(im, size, Math.min(512, Math.max(64, im.height))), roughness: 0.92, quality: 80 });
      used.set(key, name);
    }
    const q = transform(p, ([x, y, z]) => [x * S, y * S, z * S]);
    recomputeNormals(q);
    tris += triCount(q);
    pack.mesh('shell_' + p.name, uvUnit(q), used.get(key));
  }
  const obs = components(obelisk, 0.5).map(unitHeight);
  obs.forEach((o, i) => pack.mesh(`prop_obelisk_${i}`, uvUnit(o), used.get(obelisk.material)));
  console.log('sandstone shell', tris, 'tris,', parts.length, 'meshes,', obs.length, 'obelisks');
  save('sandstone.glb', pack);
}

if (!flag('--arena') && !flag('--hell1') && !flag('--hell2')) {
  console.error('usage: node scripts/prep-arena.mjs --hell1 <hell_arena_1.glb> --hell2 <hell_arena.glb> --arena <arena.glb> [--only kit|cinder|forge|sandstone] [--out dir] [--preview dir]');
  process.exit(1);
}
if (want('kit')) await buildKit();
if (want('cinder')) await buildCinder();
if (want('forge')) await buildForge();
if (want('sandstone')) await buildSandstone();
